---
title: "Agricultural Forecasting and Advisory System Report"
output: 
  pdf_document:
    includes:
      in_header: header.tex
fontsize: 12pt
geometry: margin=1in
params:
  disease: NULL
  forecast_date: NULL
  threshold: NULL
  fungicide: NULL
  growth_stage: NULL
  risk_table: NULL
---

## Specifications
- **Disease Name: **: `r params$disease`
- **Forecast Date: **: `r params$forecast_date`
- **Risk Threshold: **: `r params$threshold`%
- **No Fungicide Applied in the last 14 days?**: `r ifelse(params$fungicide, "Yes", "No")`
- **Growth Stage Within V10-R3?**: `r ifelse(params$growth_stage, "Yes", "No")`

## Summary
```{r, echo=FALSE}
library(dplyr)
library(knitr)

if (!is.null(params$risk_table) && nrow(params$risk_table) > 0) {
  # Select specific columns to display
  tarspot_table <- params$risk_table
  # Render the table
  kable(
    tarspot_table,
    caption = "Risk Trend in the last week",
    format = "markdown"
  )
} else {
  cat("No Risk data available.")
}
```


*Report Generated On: *`r format(Sys.time(), "%Y-%m-%d %H:%M")`

--------------------------------------------------------------------------------------------------------
**Note:** 
*This information is a guide, and its based on multi-year research across multiple locations to generate the models that underlay the forecast risk. Contributors and data managers assume no liability resulting from the use of these estimates. These should be used as a part of a multi-pronged approach to pest management which includes scouting and other agricultural professional insight. Individuals making decisions based on this tool assume responsibility for results on those decisions.*

**Acknowledgments:**
*This report utilizes data from the Wisconet Weather Network. We acknowledge the contributions of researchers and staff from the University of Wisconsin-Madison, who developed the Tar Spot Forecasting model and the Open Source Program Office for their support on developing this tool.*

**Contact Information:**  

- **Open Source Program Office**  
  Email: [ospo@datascience.wisc.edu](mailto:ospo@datascience.wisc.edu)

- **Dr. Damon Smith**  
  Email: [damon.smith@wisc.edu](mailto:damon.smith@wisc.edu)

- **Maria Oros**  
  Data Scientist, Data Science Institute at UW-Madison  
  Email: [moros2@wisc.edu](mailto:moros2@wisc.edu)