stations<-list(
  ANGO = list(name = 'Antigo', 
              latitude = 45.158900, 
              longitude = -89.117800, 
              location = 'Langlade County Airport', 
              region = 'Northeast', 
              county = 'Langlade', 
              earliest_api_date = '9/11/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  ALTN = list(name = 'Arlington', 
              latitude = 43.296600, 
              longitude = -89.384300, 
              location = 'Arlington Agricultural Research Station', 
              region = 'South Central', 
              county = 'Columbia County', 
              earliest_api_date = '5/22/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  RTHR = list(name = 'Arthur', 
              latitude = 45.032000, 
              longitude = -91.200000, 
              location = 'Not set', 
              region = 'Northwest', 
              county = 'Chippewa', 
              earliest_api_date = '8/28/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  BBCK = list(name = 'Babcock', 
              latitude = 44.253800, 
              longitude = -90.269000, 
              location = 'Amundson Cranberry Inc', 
              region = 'Central', 
              county = 'Wood', 
              earliest_api_date = '7/11/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  BLCR = list(name = 'Black Creek', 
              latitude = 44.481500, 
              longitude = -88.405900, 
              location = 'Fallen Timbers Environmental Center', 
              region = 'East Central', 
              county = 'Outagamie', 
              earliest_api_date = '6/12/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  WCRS = list(name = 'Black River Falls', 
              latitude = 44.185200, 
              longitude = -90.742800, 
              location = 'Black River Falls', 
              region = 'West Central', 
              county = 'Jackson', 
              earliest_api_date = '10/18/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  BRLN = list(name = 'Brillion', 
              latitude = 44.104000, 
              longitude = -88.051000, 
              location = 'Dallmann East River Dairy LLC', 
              region = 'East Central', 
              county = 'Calumet', 
              earliest_api_date = '6/11/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  BSTL = list(name = 'Bristol', 
              latitude = 42.571000, 
              longitude = -88.045000, 
              location = 'Kenosha County Center', 
              region = 'Southeast', 
              county = 'Kenosha', 
              earliest_api_date = '4/22/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  BKLN = list(name = 'Brooklyn', 
              latitude = 43.838000, 
              longitude = -89.030400, 
              location = 'Brooklyn', 
              region = 'Central', 
              county = 'Green', 
              earliest_api_date = '9/25/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  CLLK = list(name = 'Clear Lake', 
              latitude = 45.285800, 
              longitude = -92.321300, 
              location = 'Bull Brook Keep', 
              region = 'Northwest', 
              county = 'Polk', 
              earliest_api_date = '7/17/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  COSP = list(name = 'Cold Spring', 
              latitude = 42.898700, 
              longitude = -88.737200, 
              location = 'Cold Spring', 
              region = 'South Central', 
              county = 'Jefferson', 
              earliest_api_date = '10/19/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  CNDN = list(name = 'Crandon', 
              latitude = 45.522600, 
              longitude = -88.923900, 
              location = 'Crandon Municipal Airport', 
              region = 'Northeast', 
              county = 'Forest', 
              earliest_api_date = '10/23/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  CTLR = list(name = 'Cutler', 
              latitude = 44.026000, 
              longitude = -90.256000, 
              location = 'Cutler Cranberry', 
              region = 'Central', 
              county = 'Juneau', 
              earliest_api_date = '7/16/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  DEPR = list(name = 'De Pere', 
              latitude = 44.328000, 
              longitude = -87.966000, 
              location = 'Calf Source LLC', 
              region = 'East Central', 
              county = 'Brown', 
              earliest_api_date = '6/11/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  DRND = list(name = 'Durand', 
              latitude = 44.627587, 
              longitude = -91.939347, 
              location = 'Farm on Dairy', 
              region = 'West Central', 
              county = 'Pepin', 
              earliest_api_date = '10/9/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  EGHA = list(name = 'Egg Harbor', 
              latitude = 45.050900, 
              longitude = -87.259800, 
              location = 'Egg Harbor', 
              region = 'East Central', 
              county = 'Door', 
              earliest_api_date = '8/18/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  FRCD = list(name = 'Fairchild', 
              latitude = 44.609000, 
              longitude = -91.000000, 
              location = 'Fairchild', 
              region = 'Northwest', 
              county = 'Eau Claire', 
              earliest_api_date = '8/6/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  GFTN = list(name = 'Grafton', 
              latitude = 43.298100, 
              longitude = -87.932100, 
              location = 'Grafton Little League', 
              region = 'East Central', 
              county = 'Ozakee', 
              earliest_api_date = '6/18/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  GNWD = list(name = 'Greenwood', 
              latitude = 44.718000, 
              longitude = -90.596600, 
              location = 'Greenwood', 
              region = 'North Central', 
              county = 'Clark', 
              earliest_api_date = '10/17/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  HNCK = list(name = 'Hancock', 
              latitude = 44.118800, 
              longitude = -89.533300, 
              location = 'Not set', 
              region = 'Central', 
              county = 'Waushara County', 
              earliest_api_date = '2/2/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  IOLA = list(name = 'Iola', 
              latitude = 44.504026, 
              longitude = -89.024914, 
              location = 'Central County Airport', 
              region = 'Central', 
              county = 'Waupaca', 
              earliest_api_date = '10/15/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  KSKM = list(name = 'Kewaskum', 
              latitude = 43.535100, 
              longitude = -88.252700, 
              location = 'Blind Cow Dairy', 
              region = 'East Central', 
              county = 'Kewaskum', 
              earliest_api_date = '6/20/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  KWNE = list(name = 'Kewaunee', 
              latitude = 44.401800, 
              longitude = -87.664600, 
              location = 'Kewaunee', 
              region = 'East Central', 
              county = 'Kewaunee', 
              earliest_api_date = '8/24/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  KNGT = list(name = 'Knight', 
              latitude = 46.289000, 
              longitude = -90.436000, 
              location = 'Crawford Road Gravel Pit', 
              region = 'North Central', 
              county = 'Iron', 
              earliest_api_date = '7/25/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  LAFG = list(name = 'La Farge', 
              latitude = 43.597000, 
              longitude = -90.626000, 
              location = 'Kickapoo Valley Reserve Visitor Center', 
              region = 'Western', 
              county = 'Vernon', 
              earliest_api_date = '5/31/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  LNCT = list(name = 'Lancaster', 
              latitude = 42.830000, 
              longitude = -90.788200, 
              location = 'Not set', 
              region = 'Southwest', 
              county = 'Grant County', 
              earliest_api_date = '2/9/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  LXBG = list(name = 'Luxemburg', 
              latitude = 44.556000, 
              longitude = -87.654300, 
              location = 'Casco', 
              region = 'East Central', 
              county = 'Kewaunee', 
              earliest_api_date = '8/24/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  MNWT = list(name = 'Manitowish Waters', 
              latitude = 46.076000, 
              longitude = -89.838300, 
              location = 'Bartling&apos;s Manitowish Cranberry Company', 
              region = 'North Central', 
              county = 'Vilas', 
              earliest_api_date = '7/24/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  MAPL = list(name = 'Maple', 
              latitude = 46.632700, 
              longitude = -91.681200, 
              location = 'Anderson Farm', 
              region = 'Northwest', 
              county = 'Douglas', 
              earliest_api_date = '10/1/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  MRFD = list(name = 'Marshfield', 
              latitude = 44.760300, 
              longitude = -90.097800, 
              location = 'Not set', 
              region = 'North Central', 
              county = 'Marathon County', 
              earliest_api_date = '2/2/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  MNTN = list(name = 'Montana', 
              latitude = 44.401225, 
              longitude = -91.559909, 
              location = 'Bragger Family Dairy', 
              region = 'West Central', 
              county = 'Buffalo', 
              earliest_api_date = '10/10/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  MTLO = list(name = 'Montello', 
              latitude = 43.853900, 
              longitude = -89.283800, 
              location = 'Zeb Zuehls Farm', 
              region = 'Central', 
              county = 'Marquette', 
              earliest_api_date = '9/24/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  NASE = list(name = 'Nasewaupee', 
              latitude = 44.789400, 
              longitude = -87.456100, 
              location = 'Nasewaupee', 
              region = 'East Central', 
              county = 'Door', 
              earliest_api_date = '8/17/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  NBLN = list(name = 'New Berlin', 
              latitude = 42.976000, 
              longitude = -88.120000, 
              location = 'New Berlin City Hall', 
              region = 'Southeast', 
              county = 'Waukesha', 
              earliest_api_date = '7/12/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  OSEO = list(name = 'Osseo', 
              latitude = 44.590000, 
              longitude = -91.266000, 
              location = 'Osseo', 
              region = 'West Central', 
              county = 'Trempealeau', 
              earliest_api_date = '8/7/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  FFEC = list(name = 'Plover', 
              latitude = 44.446100, 
              longitude = -89.520700, 
              location = 'Food and Farm Exploration Center', 
              region = 'Central', 
              county = 'Portage', 
              earliest_api_date = '6/26/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  PLYM = list(name = 'Plymouth', 
              latitude = 43.777200, 
              longitude = -87.951500, 
              location = 'Nick Kleiber Grain', 
              region = 'East Central', 
              county = 'Sheboygan', 
              earliest_api_date = '10/30/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  GLCP = list(name = 'Porter', 
              latitude = 42.789000, 
              longitude = -89.173000, 
              location = 'Gibbs Lake County Park', 
              region = 'Southern', 
              county = 'Rock', 
              earliest_api_date = '5/23/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  DFRC = list(name = 'Prairie du Sac', 
              latitude = 43.344800, 
              longitude = -89.711700, 
              location = 'Prairie du Sac', 
              region = 'Southwest', 
              county = 'Sauk', 
              earliest_api_date = '9/28/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  RNLD = list(name = 'Rhinelander', 
              latitude = 45.654600, 
              longitude = -89.268200, 
              location = 'Not set', 
              region = 'North Central', 
              county = 'Oneida County', 
              earliest_api_date = '2/2/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  RCHD = list(name = 'Richland Center', 
              latitude = 43.370000, 
              longitude = -90.383000, 
              location = 'Richland County Highway Department', 
              region = 'Southern', 
              county = 'Richland', 
              earliest_api_date = '5/30/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  RIPN = list(name = 'Ripon', 
              latitude = 43.905600, 
              longitude = -88.846700, 
              location = 'Vines and Rushes Winery', 
              region = 'East Central', 
              county = 'Winnebago', 
              earliest_api_date = '6/10/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  SIBA = list(name = 'Sister Bay', 
              latitude = 45.219100, 
              longitude = -87.066200, 
              location = 'Sister Bay', 
              region = 'East Central', 
              county = 'Door', 
              earliest_api_date = '8/18/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  STAR = list(name = 'Soldiers Grove', 
              latitude = 43.378400, 
              longitude = -90.900000, 
              location = 'Star Valley Flowers', 
              region = 'Southwest', 
              county = 'Crawford', 
              earliest_api_date = '9/12/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  SMKE = list(name = 'South Milwaukee', 
              latitude = 42.901300, 
              longitude = -87.851200, 
              location = 'South Milwaukee Wastewater Treatment Plant', 
              region = 'Southeast', 
              county = 'Milwaukee', 
              earliest_api_date = '9/27/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  SODO = list(name = 'Southern Door', 
              latitude = 44.779000, 
              longitude = -87.355600, 
              location = 'Sturgeon Bay', 
              region = 'East Central', 
              county = 'Door', 
              earliest_api_date = '8/17/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  SPNR = list(name = 'Spooner', 
              latitude = 45.827000, 
              longitude = -91.861400, 
              location = 'Not set', 
              region = 'Northwest', 
              county = 'Washburn County', 
              earliest_api_date = '2/9/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  PARS = list(name = 'Sturgeon Bay', 
              latitude = 44.880200, 
              longitude = -87.329600, 
              location = 'Sturgeon Bay', 
              region = 'East Central', 
              county = 'Door', 
              earliest_api_date = '8/17/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  SRNG = list(name = 'Suring', 
              latitude = 44.999000, 
              longitude = -88.342700, 
              location = 'Mahoney Farms', 
              region = 'Northeast', 
              county = 'Oconto', 
              earliest_api_date = '10/22/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  #MITEST1 = list(name = 'Usonia_II', 
  #               latitude = 42.714010, 
  #               longitude = -84.453500, 
  #               location = 'Not set', 
  #               region = '', 
  #               county = '', 
  #               earliest_api_date = '7/1/2023', 
  #               time_zone = 'US/Eastern', 
  #              state = 'MI'),
  VLDR = list(name = 'Valders', 
              latitude = 44.004400, 
              longitude = -87.822800, 
              location = 'Libertyland Farms', 
              region = 'East Central', 
              county = 'Manitowoc', 
              earliest_api_date = '10/29/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  OJNR = list(name = 'Verona', 
              latitude = 43.025000, 
              longitude = -89.536700, 
              location = 'Verona', 
              region = 'South Central', 
              county = 'Dane', 
              earliest_api_date = '9/28/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  DUDA = list(name = 'Walworth', 
              latitude = 42.527000, 
              longitude = -88.640000, 
              location = 'Blooming Duda&apos;s Flower Farm', 
              region = 'Southeast', 
              county = 'Walworth', 
              earliest_api_date = '5/22/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  WRNS = list(name = 'Warrens', 
              latitude = 44.116700, 
              longitude = -90.412100, 
              location = 'Weatherby Cranberry Company', 
              region = 'West Central', 
              county = 'Monroe', 
              earliest_api_date = '7/1/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  WJPT = list(name = 'West Jacksonport', 
              latitude = 45.010000, 
              longitude = -87.233500, 
              location = 'West Jacksonport', 
              region = 'East Central', 
              county = 'Door', 
              earliest_api_date = '8/18/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  WTBG = list(name = 'Wittenberg', 
              latitude = 44.866000, 
              longitude = -89.023550, 
              location = 'Strassburg Creek Dairy', 
              region = 'Northeast', 
              county = 'Shawano', 
              earliest_api_date = '10/23/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  KEMP = list(name = 'Woodruff', 
              latitude = 45.841000, 
              longitude = -89.667800, 
              location = 'Woodruff', 
              region = 'North Central', 
              county = 'Oneida County', 
              earliest_api_date = '9/27/2023', 
              time_zone = 'US/Central', 
              state = 'WI'),
  WDVL = list(name = 'Woodville', 
              latitude = 44.943000, 
              longitude = -92.287000, 
              location = 'Viking Middle School', 
              region = 'West Central', 
              county = 'St. Croix', 
              earliest_api_date = '8/27/2024', 
              time_zone = 'US/Central', 
              state = 'WI'),
  UGRV = list(name = 'Yorkville', 
              latitude = 42.728100, 
              longitude = -88.028000, 
              location = 'Racine Astronomical Society', 
              region = 'Southeast', 
              county = 'Racine', 
              earliest_api_date = '9/5/2024', 
              time_zone = 'US/Central', 
              state = 'WI')
)